server:
  port: 7001

spring:
  application:
    name: nacos-client-coupon-template
  main:
    allow-bean-definition-overriding: true
  datasource:
    # 数据源
    url: jdbc:mysql://127.0.0.1:3306/imooc_coupon_data?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    hikari:
      maximum-pool-size: 8
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: ImoocCouponHikariCP

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    # password:
    # 连接超时时间
    timeout: 10000

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: BJ


#feign的配置
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        loggerLevel: full
  #        requestInterceptor:
  #          - com.springcloud.alibaba.feignclient.interceptor.TokenRelayRequestInterceptor
  httpclient:
    # 让feign使用apache httpclient做请求，而不是默认的urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign的单个路径的最大连接数
    max-connections-per-route: 50

# ------------------------------------------------------------------------------------------------------

management:
  endpoints:
    web:
      exposure:
        include: "*"


# ------------------------------------------------------------------------------------------------------

logging:
  level:
    com.alibaba.coupon: debug

# -------------------------------------------------------------------------------------------------
# mybatis的类型转换器
mybatis:
  type-handlers-package: com.alibaba.coupon.domain.converter

